---
- hosts: webservers
  sudo: yes
  tasks:
     - name: install apache2 on ubuntu
       apt: name=apache2 update_cache=yes state=latest
     - name: copy index.html to ubuntu  webservers
       copy: src=/etc/ansible/index.html dest=/var/www/html/index.html
